### ISSUE TITLE
Lesson 20: Back to the drawing board. "Rectangles have the correct size" check failing with suggested solution.

### ISSUE THREAD

**Issue by atarias1** [GDQuest/learn-gdscript#544] opened 2022-06-08 20:06 UTC
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
"Rectangles have the correct size" check failing with suggested solution. This happens even with other correct solutions.

**What is the expected behavior?**
Using the suggested solution should satisfy the check. 

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment] 2022-06-08 20:09
Duplicate of #522

**Closed by NathanLovato** 2022-06-08 20:09 UTC
Labels: duplicate
