### ISSUE TITLE
20: Looping over arrays

### ISSUE THREAD

**Issue by pfargo** [GDQuest/learn-gdscript#538] opened 2022-06-06 11:00 UTC
**I'm submitting a...** 

- [ X] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
2nd practice session crashes app regardless of what follows "for rect in rectangle_sizes"

**What is the expected behavior?**
No crash

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

<pre><code>
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for rect in rectangle_sizes:
		print(rect)
</code></pre>

* The code runs and output is correct but then the app crashes (regardless of what is in the for loop).

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 

Running the standalone app latest update on windows 10

**Comment by NathanLovato** [comment] 2022-06-06 12:10
Duplicate of #500

**Closed by NathanLovato** 2022-06-06 12:10 UTC
Labels: duplicate
