### ISSUE TITLE
Sup, the 'game' crashed twice on the last practice of level 10

### ISSUE THREAD

**Issue by ghostOfStPeter** [GDQuest/learn-gdscript#628] opened 2022-08-22 16:49 UTC
I was fucking about with the x and y values and the game would crash

Steps to reproduce the bug:
1. Go to level 10
2. Click on practice
3. fuck around
4. See game crash

the game would run the code as intended but would crash soon after

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: no, exe version

here's the log you beauties

{"time":"","level":10,"msg":"INIT","OS":"Windows","datetime":{"year":2022,"month":8,"day":22,"weekday":1,"dst":true,"hour":18,"minute":42,"second":41},"video_driver":"GLES2","video_adapter":"NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2","video_vendor":"NVIDIA Corporation","screen_size":"(1920, 1080)","screen_dpi":96,"cores":4,"locale":"en_GB","joypad":""}
{"time":"","level":30,"msg":"loaded profile","id":"440c85fe-9558-44a6-8174-9d5c3a96fd87","profileName":"Player"}

**Comment by NathanLovato** [comment] 2022-08-23 05:05
Could you please share exactly the code that crashes the app? Without precise reproduction steps, we can't address the issue.

**Comment by NathanLovato** [comment] 2022-08-23 05:14
For now, I'll assume this is related to #618 and close the issue as we can't use it, but if the cause is different and you can share code to trigger the crash, that'd be great if you can share it. Thanks for the report regardless

**Closed by NathanLovato** 2022-08-23 05:14 UTC
Labels: bug
