### ISSUE TITLE
Lesson 8 practice 1 completes with any value assigned

### ISSUE THREAD

**Issue by johnnygossdev** [GDQuest/learn-gdscript#116] opened 2022-01-05 15:54 UTC
**Describe the bug**
In lesson 8 practice 1, any value of health results in a correct completion. Only a value of `100` should be accepted.

**To Reproduce**
Assign any value other than `100` to the health value in lesson 8, practice 1.

**Screenshots**
In this example, I used a value of `99`.

![lesson-8-error](https://user-images.githubusercontent.com/3285214/148247162-dfec24f3-1768-4bdd-8b62-da0e0d666f53.png)

**Information about your device (please complete the following information):**
 - Windows
 - Browser/run locally

**Comment by johnnygossdev** [comment] 2022-01-05 15:55
This relates to #86 as lesson 12 also checks variable values.

**Comment by duianto** [comment] 2022-01-05 16:27
This doesn't mention lesson 8, but it seems to be referring to the same issue:
On first run, an assignment checking a variable’s initial value can be right even if student code isn’t #13

**Comment by johnnygossdev** [comment] 2022-01-05 16:31
You are indeed correct. This is a duplicate.

**Comment by NathanLovato** [comment] 2022-01-05 20:12
I'll close this as it's a duplicate. Yeah, we've seen this, we gotta investigate the cause. It seems it uses the existing variable definition in the slice on the first run.

**Closed by NathanLovato** 2022-01-05 20:12 UTC
Labels: bug, duplicate
