### ISSUE TITLE
Lesson 15 Modulo: traffic light advance() button not working in example

### ISSUE THREAD

**Issue by dholl** [GDQuest/learn-gdscript#683] opened 2022-10-01 16:36 UTC
**Describe the bug**
In lesson 15, the advance() button does not work on either of the traffic light examples.  In both cases, light_index appears to stay at 0, and the traffic light stays red.

**To Reproduce**
Steps to reproduce the bug:
1. Click on the advance() button.
4. See that the traffic light stays red

**Expected behavior**
I expected the traffic light to cycle to another color when clicking advance()

**Screenshots**
<img width="417" alt="traffic_light_stuck" src="https://user-images.githubusercontent.com/4298582/193419094-71714e43-ae58-4a1e-9449-a38afe00d7d6.png">

<img width="423" alt="traffic_light_stuck_2" src="https://user-images.githubusercontent.com/4298582/193419072-3f642f59-9309-4f8a-b717-c2507cf7575c.png">

**Information about your device (please complete the following information):**
 - Operating System: macOS 12.6 Monterey, Darwin Kernel Version 21.6.0 x86_64
 - Browser: Firefox 105.0.1 (64-bit)

**Additional context**
Attached log:
[gdquest-1664641492985.log](https://github.com/GDQuest/learn-gdscript/files/9690759/gdquest-1664641492985.log)

Is there anything else I may contribute to help reproduce the problem?

Thank you,
David

**Comment by Wolfy7** [comment] 2022-10-03 11:05
Already labeled as `duplicate`

Its a duplicate of #679, just a comment to link them together.

**Comment by NathanLovato** [comment] 2022-10-10 14:35
Fixed by #696

**Closed by NathanLovato** 2022-10-10 14:35 UTC
Labels: bug, duplicate, good first issue, hacktoberfest
