### ISSUE TITLE
Incorrect label in Lesson 6

### ISSUE THREAD

**Issue by Hexb0y** [GDQuest/learn-gdscript#494] opened 2022-04-15 20:18 UTC
**Issue description:**
Inside of the "**How should I name my functions and parameters?**" window, the word _type_ is mistakenly identified as referring to a variable type in a programming language. In the given context, it is referring to the action of typing on a keyboard. Users can click on it in this instance and receive an explanation of variable types.
The typo in question is highlighted with a red exclamation mark at the bottom of the screenshot.
![Typo](https://user-images.githubusercontent.com/92604980/163627860-31f8080b-228e-4cc2-bc58-07c6395777cb.PNG)

The same error can also be found in the last line as well.
![Typo2](https://user-images.githubusercontent.com/92604980/163628850-c8c5c2a2-a8cd-40e9-8fe0-2aba3de4deb5.PNG)

**Comment by NathanLovato** [comment] 2022-04-16 05:54
Duplicate of #446

**Closed** 2022-06-10 10:25 UTC
Labels: duplicate, content
