### ISSUE TITLE
Unsupported error

### ISSUE THREAD

**Issue by Hollow1364781653786** [GDQuest/learn-gdscript#858] opened 2023-09-20 16:23 UTC
the line 
     for cell.y in range(board.size.y - 1):
brings out the issue below:
"in" expected after identifier.

And it says that the issue isn't covered yet and asks to report it, so here i am, reporting it! 

(it's the 18th lesson, if that makes any difference)
![Screenshot_1254](https://github.com/GDQuest/learn-gdscript/assets/100510026/a5f1438f-1385-4616-9769-0034ead8ca25)

**Comment by NathanLovato** [comment] 2023-09-30 06:54
Closing as duplicate of #838. Thanks for the report nonetheless!

**Closed by NathanLovato** 2023-09-30 06:54 UTC
Labels: duplicate, content
