### ISSUE TITLE
Game Freeze if User 'Stays' in Lesson 'Creating Circular Movement'

### ISSUE THREAD

**Issue by Mosscairn** [GDQuest/learn-gdscript#600] opened 2022-07-31 01:04 UTC
**The Issue**
Upon running the code in this lesson for a second time, the window contents become unresponsive. This happens after a few moments of the code running as expected. (my shot in the dark is that perhaps it's caused by the condition checker?)
The cursor still recognizes the buttons on mouse over of course, but besides that nothing on the page will react to any user input.*
\* With one exception: For some reason, the fullscreen button in the top-right remains functional.

**Steps To Reproduce**
1. Go to ['Creating Circular Movement'](https://gdquest.github.io/learn-gdscript/#course/lesson-10-the-game-loop/practice-QiGjB7tK.tres)
2. Solve the assignment
3. Click on 'Stay'
4. Run code again
5. Ui becomes unresponsive

* It seems to be quite easy to replicate. At least on my end it works every time.

**Expected behavior**
The page runs the code, returns any errors, and allows the user to proceed with the course.

**Screenshots**
The page is frozen. Note the greyed-out buttons. Nothing I do here will have an effect. (Including the 'Output' button, menu icons, etc.)
![Frozen Page](https://user-images.githubusercontent.com/54695659/182005116-b2e24408-a9ca-4897-aeeb-bebe1ff46be3.png)

With the exception of the fullscreen button, which was just used here while the page was still unresponsive.
![Fullscreen Button Works](https://user-images.githubusercontent.com/54695659/182005125-e4d836af-e0fb-4976-bc48-a169e2dbb7ad.png)

**Device Info:**
 - Operating System: Windows 10 (Ver. 10.0.19044)
 - Browser: Chrome (Ver. 103.0.5060.134)
 
 *I hope this report is helpful! loving this tool so far, it's a great refresher and the tutorial godot robo is such a cute lil dude just vibin ^^*

**Comment by Mosscairn** [comment] 2022-07-31 01:06
Oh, and sorry I couldn't generate an error log haha. I'm not sure if there's a way to get to it without the ability to click on the report button while the page is frozen.

**Comment by NathanLovato** [comment] 2022-07-31 06:14
Duplicate of #560

**Closed by NathanLovato** 2022-07-31 06:14 UTC
Labels: bug
