### ISSUE TITLE
UI break

### ISSUE THREAD

**Issue by subarutendou** [GDQuest/learn-gdscript#827] opened 2023-06-06 02:33 UTC
**Describe the bug**
The UI of the exercise cut off if the text size is bigger then default, this happen to 14-2. This is where I'm learning, and is the first time the UI break though the border of the monitor.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Setting'
2. make text bigger
3. apply

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.
![スクリーンショット (107)](https://github.com/GDQuest/learn-gdscript/assets/47707894/a1c44782-2771-481e-b2a9-264321dde5f0)

**Information about your device (please complete the following information):**
 - Operating System: [Windows]

**Comment by NathanLovato** [comment] 2023-09-29 12:40
Thanks for the report, closing as it's a duplicate of #785

**Closed by NathanLovato** 2023-09-29 12:40 UTC
Labels: bug, duplicate
