### ISSUE TITLE
Typo in Lesson 7

### ISSUE THREAD

**Issue by emshuttles** [GDQuest/learn-gdscript#777] opened 2023-02-07 21:48 UTC
In Lesson 7 section "Accessing sub-variables with the dot", there is a typo in the sentence right before the code sample. The variable values in the sentence are different from the ones in the code sample.
![typo](https://user-images.githubusercontent.com/29593197/217374324-eb454a62-2f08-44a3-8ec1-cf079db0f7e4.PNG)

**Comment by Alylaxy** [comment] 2023-03-02 13:30
Duplicate of #773, which was supposed to be fixed (codewise it is, but i dont think github pages made another build)

**Closed** 2023-10-01 08:51 UTC
Labels: content
