### ISSUE TITLE
Lesson 19

### ISSUE THREAD

**Issue by MilesFarber** [GDQuest/learn-gdscript#839] opened 2023-07-15 13:25 UTC
![image](https://github.com/GDQuest/learn-gdscript/assets/24918282/0861efbe-8226-4859-b77c-af295b442780)
Um.... no there aren't?

**Comment by NathanLovato** [comment] 2023-09-29 14:38
It appears to be fixed in the latest version. Closing as we can't reproduce the issue anymore.

When you report issues, could you please use the issue template so we know the system and version you're using? It helps us to check if they exist on a specific system or version of the app.

**Closed by NathanLovato** 2023-09-29 14:38 UTC
Labels: bug
