### ISSUE TITLE
Modulo % symbol missing

### ISSUE THREAD

**Issue by deltreey** [GDQuest/learn-gdscript#619] opened 2022-08-11 23:26 UTC
**Issue description:**
On lesson 15, in the Dice Example, the % symbol is not visible on the page

![https://i.imgur.com/pP5oKtr.png](https://i.imgur.com/pP5oKtr.png)

I deleted and re-entered the text, and have a commit that seems to fix it, at least in local testing.

**Comment by NathanLovato** [comment] 2022-08-12 12:09
It's not going to cut it, the issue is broader than that, see #99. I don't want to address this for each code block individually because it depends on the font size setting, so you can't quite nail it.

One thing we could do instead is to allow resizing the lesson column, which would give the text and examples more space, and limit wrapping, limiting the issue. That'd at least address more occurrences of this. That aside, basically we're waiting for Godot 4 and the new and more robust text layout engine to fix this.

Closing as it's part of #99

**Closed by NathanLovato** 2022-08-12 12:09 UTC
Labels: content
