### ISSUE TITLE
Lesson 11 doesn't accept correct answer

### ISSUE THREAD

**Issue by AbsoluteVirtue** [GDQuest/learn-gdscript#490] opened 2022-04-10 18:53 UTC
**Second practical part of the Time Delta lesson**
The task is to make the character move and rotate by a certain amount. Replacing integers with floats in the argument list where a float is expected will cause the code to fail the tests. Changing the order of the operands will also cause the tests to fail.

**To Reproduce**
The following code won't pass the tests.

```
   func _process(delta):
	  rotate(delta * 2)
	  move_local_x(delta * 100)
```

The solution shows the following code.

```
  func _process(delta):
	  rotate(2 * delta)
	  move_local_x(100 * delta)
```

These two solutions are equivalent and should be accepted regardless of the order of the operands. What's even more interesting is that this solution which is also equivalent doesn't pass 2 tests out of 3.

```
  func _process(delta):
	  rotate(delta * 2.0)
	  move_local_x(delta * 100)
```

**Expected behavior**
Ideally, the order of the operands shouldn't matter, since most people doing this course are familiar with the commutative rule for the multiplication operator.

**Screenshots**
![image](https://user-images.githubusercontent.com/10259517/162634760-17e7454d-8927-4352-9fe9-d040910ed88c.png)
![image](https://user-images.githubusercontent.com/10259517/162635055-e3a88ad3-6be5-4e62-b017-a6389aa4fb82.png)

**Comment by NathanLovato** [comment] 2022-04-11 07:40
Duplicate of #488, already fixed. I'll make a new stable release this week so everyone gets the latest fixes

**Closed by NathanLovato** 2022-04-11 07:40 UTC
Labels: bug, duplicate
