### ISSUE TITLE
fix: Answer-checking on Lesson 20 bugged

### ISSUE THREAD

**Issue by TriAttack238** [GDQuest/learn-gdscript#460] opened 2022-03-20 03:44 UTC
**Describe the bug**
On Lesson 20 practice "Back to the drawing board" solutions which fulfill the requirements(rectangles are there correct size, rectangles do not overlap) are incorrectly declared as wrong, including the provided solution. For every case I've seen so far the program declares that the rectangles do not have the correct size.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 20 either by proceeding forward with the curriculum or clicking in the course index.
2. Proceed to practice 2: "Back to the Drawing Board"
3. Write code to solve the problem and press "Run", or press "Solution", "Use Solution", and then "Run".

**Expected behavior**
I expected for the solution to be able to solve the problem, which it clearly does as seen in the output monitor. 

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

![GDQuest_1](https://user-images.githubusercontent.com/101959987/159147132-b2bda6f8-7a7a-40b7-83ac-ad2b141b5c26.PNG)

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]
Windows 10, Google Chrome

**Additional context**

**Comment by NathanLovato** [comment] 2022-03-20 08:58
Duplicate of #452

**Closed by NathanLovato** 2022-03-20 08:58 UTC
Labels: bug
