### ISSUE TITLE
Lesson 19. Creating Arrays - Should be Square Bracket

### ISSUE THREAD

**Issue by cramsey86** [GDQuest/learn-gdscript#457] opened 2022-03-19 18:27 UTC
In "The syntax of arrays" it says "You start with an opening **angular** bracket" and subsequent "closing **angular** bracket". This should be "**square** brackets".

**Comment by NathanLovato** [comment] 2022-03-20 08:58
Already fixed, duplicate of #449

**Closed by NathanLovato** 2022-03-20 08:58 UTC
Labels: duplicate, content
