### ISSUE TITLE
Jump Demonstration Inconsistency

### ISSUE THREAD

**Issue by Syweb2** [GDQuest/learn-gdscript#470] opened 2022-03-26 05:07 UTC
**Issue description:**
In the lesson "Your first function", there is a section in the text where an animation demonstrates a function called jump(). According to the text, jump(-100,50) should move the turtle _down_ and to the left, however, when it runs, each of the three instances move the turtle _up_ to its origin point, as shown in the attached image. I feel this may confuse viewers, as the animation is inconsistent with the text's description.
![inconsistency_jump_function](https://user-images.githubusercontent.com/54687034/160225586-e87ab8fc-41a2-40df-89eb-9d7f57de1d4d.JPG)

**Comment by NathanLovato** [comment] 2022-03-26 08:58
Duplicate of #465

**Closed by NathanLovato** 2022-03-26 08:58 UTC
Labels: duplicate, content
