### ISSUE TITLE
When I removed my ad blocker it removed all my progress

### ISSUE THREAD

**Issue by Raxvier** [GDQuest/learn-gdscript#207] opened 2022-01-29 07:22 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:

**Expected behavior**

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

**Information about your device (please complete the following information):**
 - Operating System: [e.g. iOS, Windows]

**Additional context**

**Comment by pycbouh** [comment] 2022-01-29 10:06
Your ad blocker probably created a container for browser storage (it's a feature to avoid tracking your internet activity). Disabling it means all the stored data is no longer accessible. There is nothing we can do about it, it's your ad blocker working as intended.

**Comment by NathanLovato** [comment] 2022-10-04 14:46
I left this issue open mostly to see if other people would have the same. People didn't report the same issue since then, so closing for now.

**Closed by NathanLovato** 2022-10-04 14:46 UTC
Labels: wontfix
