### ISSUE TITLE
Bug on 20. Looping Over Arrays

### ISSUE THREAD

**Issue by mrfisty** [GDQuest/learn-gdscript#530] opened 2022-05-31 23:31 UTC
**Describe the bug**
Although the code is the same as the proposed solution, it's returning an error message: "At least one of the rectangles does not have the expected size."

**Expected behavior**
Should run without error.

![godot_quest_bug_lesson_20_01](https://user-images.githubusercontent.com/4332336/171300080-c0f7a4f6-ead3-4bd8-95c0-bc3576be3a26.png)

![godot_quest_bug_lesson_20_02](https://user-images.githubusercontent.com/4332336/171300091-657125b4-899e-4bfa-9b30-bd9a8f9c7128.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: FireFox

**Log**: 
[gdquest-1654039522884.log](https://github.com/GDQuest/learn-gdscript/files/8810455/gdquest-1654039522884.log)

**Comment by NathanLovato** [comment] 2022-06-02 13:13
I see, it's a duplicate of #522, seems like the same navigation issue where some state doesn't update when the practice isn't correct on the first attempt. Closing this and leaving the original issue open

**Closed by NathanLovato** 2022-06-02 13:13 UTC
Labels: bug, duplicate
