### ISSUE TITLE
Lesson 17: Mismatch between variables in lesson/documentation and lesson solution

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#390] opened 2022-03-01 21:04 UTC
In the lecture text we talk about _board_size_. Same goes for the practice text and documentation.
The actual solution needs just _size_ to work although it should be _board_size_ as well.

**Comment by NathanLovato** [comment] 2022-03-02 07:13
Duplicate of #378, already fixed

**Closed by NathanLovato** 2022-03-02 07:13 UTC
Labels: duplicate, content
