### ISSUE TITLE
Lesson 26 phantom variable

### ISSUE THREAD

**Issue by MilesFarber** [GDQuest/learn-gdscript#840] opened 2023-07-15 16:03 UTC
![image](https://github.com/GDQuest/learn-gdscript/assets/24918282/a6492e80-999e-4ae1-abfd-5815398b4b45)
`for cell in units:`???
Where in the world is it getting `cell` from if `cell` has NEVER been declared???

**Comment by Visnicio** [comment] 2023-07-18 12:36
On the suggested solution, the variable `cell` is inferred by the interpreter as the "current element being looped" so it does not need to be declared,
Lesson 19 has a quick explanation about this:

![image](https://github.com/GDQuest/learn-gdscript/assets/70033167/fc2f5af3-79e4-4b46-af16-ade64157d23f)

It's sorta like a "runtime declaration"

**Comment by MilesFarber** [comment] 2023-07-19 07:44
![image](https://github.com/GDQuest/learn-gdscript/assets/24918282/c8d3c30f-a7b3-4eaf-8c11-0f14aa852985)
When will "Runtime declarations" be included in the documentation tab to the left of exercises so future students don't have to randomly guess the name?

**Comment by Visnicio** [comment] 2023-07-19 11:31
My point is that your code failed the tests 'cause of the parameter that you passed to the `place_unit` function:
![image](https://github.com/GDQuest/learn-gdscript/assets/70033167/47325045-fd32-475e-83dd-d983315f7277)

Your nor the suggestion naming should be the cause of tests failed, for your code to work you should have passed the position and then the unit string as described in the lesson.

So, by refactoring your code I got something like
```gdscript
for vector in units:
    var cell = units[vector]
    place_unit(vector, cell)
``` 
Although this code now works, it's not efficient because of the naming, naming variables is a hard task and many developers struggle with it (me included)

**Comment by MilesFarber** [comment] 2023-07-19 12:46
> Although this code now works, it's not efficient because of the naming, naming variables is a hard task and many developers struggle with it (me included)

Whether it's efficient or not is **completely irrelevant**. That is the ONLY code that should work because nowhere anywhere in the entire course are "runtime declarations" explained properly, nor does the course ever show the student the documentation for what ALL the "member variables" are, which would speed up development by many orders of magnitude, no matter what the project is.

![image](https://github.com/GDQuest/learn-gdscript/assets/24918282/efcf6802-b4c5-4211-8bd2-1397076753ab)
I guess i'm just not one of those developers.

**Comment by Visnicio** [comment] 2023-07-19 13:03
Just to put us on the same page: "Runtime Variables" is no official naming or concept, it's just a way that I found to try to make it clear

The student is not left by himself.
Indeed, the lessons about for loops could enforce more that the variables are implicit, but I feel that lesson 19 already made it pretty clear that in a `for` loop you have to declare a variable that will represent the current element of the loop. Sure, you can definitely name it "dab" but why would you? When writing any loop, you first have to understand why and what are you looping though.

`func run()` is not a native function of the Godot Engine, so I do not see your point here that "it's not in the docs", again, lesson 19 explains that a `for` loop receives a variable that represents the current element of the loop, the programmer could name anything he would like. So, getting back again to the first question: `cell` was not a defined variable, it was inferred by the loop, it's just how the language works

**Comment by NathanLovato** [comment] 2023-07-20 11:01
>  Where in the world is it getting cell from if cell has NEVER been declared???

Writing `for cell in units` declares `cell`.

I invite you to revisit [lesson 18](https://gdquest.github.io/learn-gdscript/#course/lesson-18-for-loops/lesson.tres) and the following lesson 19 where we introduce for loops and the temporary variable you declare and name as part of the loop expression.

If you do take the time to revisit them, it'd be great if you could share a bit of feedback if you find something particularly confusing. Different people struggle with very different parts of programming courses, and while this app received lots of iterations and feedback, we're looking to improve the course with its upcoming Godot 4 remake.

**Comment by NathanLovato** [comment] 2023-09-29 14:34
Closing for now as I believe the raised point is covered in the course. Though I understand the frustration, of course, it's easy to miss or forget something, and the app doesn't have a lot of repetition built-in. It's something we hope to improve over time with its future replacement.

**Closed by NathanLovato** 2023-09-29 14:34 UTC
Labels: bug
