### ISSUE TITLE
Shortcuts on mac with Cmd don't work. Ctrl required as on Windows

### ISSUE THREAD

**Issue by tim-mukhin** [GDQuest/learn-gdscript#1024] opened 2024-11-25 15:38 UTC
**Describe the bug**
Wrong shortcuts on mac: copy, paste, cut, undo. Basically any cmd-prefixed shortcuts would work incorrectly. It's very annoying.
Instead of using Cmd it requires to use Ctrl as on Windows, which is incorrect.

**To Reproduce**
Steps to reproduce the bug:
Open any practice on mac and try to copy text from anywhere in the practice page (description or editor) with Cmd+C. 

**Expected behavior**
Text copied to clipboard

**Information about your device (please complete the following information):**
 - Operating System: Macos
 - Browser: Chrome

**Comment by NathanLovato** [comment] 2024-11-26 14:33
This is a known limitation that's not simple to fix. See #711 for more information.

Closing as this is a duplicate of #711

**Closed by NathanLovato** 2024-11-26 14:33 UTC
Labels: bug, duplicate
