### ISSUE TITLE
Modulo - Display problem in code sample

### ISSUE THREAD

**Issue by denicolas** [GDQuest/learn-gdscript#727] opened 2022-10-27 18:48 UTC
[Modulo](https://gdquest.github.io/learn-gdscript/?ref=godot-docs#course/lesson-15-modulo/lesson.tres)

In "**Calculating a random number within a range**", on my Linux (Kubuntu) computer, using the Chromium browser, or Firefox, the code sample is truncated, '%' doesn't show:
![Screenshot_modulo_hidden](https://user-images.githubusercontent.com/73497614/198372669-fccdf019-8ab9-49f5-9569-dbbeb0dfd8d5.png)

### Workaround:
"**Configure the app**" icon > **Text Size**: decrease, **[Apply]**, **[Close]**
'%' is now shown:
![Screenshot_modulo_shown](https://user-images.githubusercontent.com/73497614/198372804-53078307-840e-40f6-9bac-b2130572c2e4.png)

Actually, if you now go back to the original text size, '%' is still shown:
![Screenshot_modulo_shown2](https://user-images.githubusercontent.com/73497614/198372877-966e6859-30de-4bf9-9072-23a0a864a80f.png)

**Comment by NathanLovato** [comment] 2022-10-28 05:23
Duplicate of #99, it's an engine-side issue we can't solve on our end

**Closed by NathanLovato** 2022-10-28 05:23 UTC
Labels: bug, duplicate
