### ISSUE TITLE
Lesson 20: Mismatch between pre-declared array and array used in solution

### ISSUE THREAD

**Issue by SpeCter** [GDQuest/learn-gdscript#391] opened 2022-03-01 22:18 UTC
The pre-declared array for the practice is missing a value:
`var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140)]`

vs. solution array:

`var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]`

**Comment by NathanLovato** [comment] 2022-03-02 06:29
Already fixed, duplicate of #385

**Closed by NathanLovato** 2022-03-02 06:29 UTC
Labels: content
