### ISSUE TITLE
Content text overlapping with headers

### ISSUE THREAD

**Issue by BliznyukNM** [GDQuest/learn-gdscript#447] opened 2022-03-11 19:49 UTC
**Describe the bug**
When scrolling text inside middle section goes on top of the header. It happens not constantly, next scroll will hide some text, some text will still be there.

**To Reproduce**
Steps to reproduce the bug:
1. Go to index page
2. Scroll content of this page

**Expected behavior**
Text stays inside it's section

**Screenshots**
![image](https://user-images.githubusercontent.com/46704931/157948018-c4edee29-1c9d-42d9-b0b6-9ab4f2d6d136.png)

**Information about your device (please complete the following information):**
 - Operating System: macOS Monterey 12.2.1
 - Browser: Safari 15.3

**Additional context**
None

**Comment by NathanLovato** [comment] 2022-03-12 07:14
That's a known issue, unfortunately it's a Safari-specific problem and we don't know how to solve it - there'd probably need to be a Safari-specific fix in the Godot engine itself.

Closing, duplicate of #185

**Closed by NathanLovato** 2022-03-12 07:14 UTC
Labels: bug
