### ISSUE TITLE
Fullscreen button starts off in the wrong state

### ISSUE THREAD

**Issue by scottwestover** [GDQuest/learn-gdscript#525] opened 2022-05-19 02:22 UTC
**Describe the bug**
When visiting the application on the web, https://gdquest.github.io/learn-gdscript/, the web app is showing that the application is already in fullscreen mode when the page first loads. If I click on the button to make the app fullscreen, nothing happens in the app.

If I manually resize my browser window so that it is no longer maximized, the button changes to show the app can toggled into full screen mode. If I click the button, the app expands and takes up my full screen as expected. If I leave the fullscreen view, and maximize my browser the button switches to show I am in full screen mode and I am not able to have the app take up the full screen properly.

**To Reproduce**
Steps to reproduce the bug:
1. Navigate to https://gdquest.github.io/learn-gdscript and make sure your browser window is already maximized
2. Click on the make fullscreen button in the app and nothing with happen
3. Manually resize your browser window so it is no longer maximized
4. Click on the make fullscreen button in the app and the app will take up the full screen as expected

**Expected behavior**
When visiting the site, the make fullscreen button should always have the app take up the full screen of the browser and the button should not show the app is already in fullscreen when the button has not been clicked.

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

Example of the button not working when the browser is already maximized:
<img width="1440" alt="Screen Shot 2022-05-18 at 10 09 25 PM" src="https://user-images.githubusercontent.com/9931822/169189219-164980a7-8ed5-4c89-97c3-e563283c70de.png">

Example of the button showing correctly when the browser is not maximized:
<img width="1440" alt="Screen Shot 2022-05-18 at 10 09 19 PM" src="https://user-images.githubusercontent.com/9931822/169189321-f9ab68b7-f494-4c9b-90f0-e58ef30b265d.png">

Example video showing the bug:

https://user-images.githubusercontent.com/9931822/169189472-77cb324e-1280-48db-8a3a-4cf7a102e4ce.mov

**Information about your device (please complete the following information):**
 - Operating System: macOS Mojave - version 10.14.6
 - Browser: Chrome - Version 101.0.4951.54

**Additional context**
Attaching error log.
[gdquest-1652925828385.log](https://github.com/GDQuest/learn-gdscript/files/8722924/gdquest-1652925828385.log)

**Comment by NathanLovato** [comment] 2022-06-08 20:10
Is this still happening? I can't reproduce the issue.

**Comment by NathanLovato** [comment] 2022-06-10 08:34
Closing for now as we can't reproduce the issue, but if you still have the bug, please let me know and we'll reopen.

**Closed by NathanLovato** 2022-06-10 08:34 UTC
Labels: bug
