### ISSUE TITLE
Copy-Paste bug

### ISSUE THREAD

**Issue by lukaszml** [GDQuest/learn-gdscript#721] opened 2022-10-25 12:56 UTC
**Describe the bug**
While trying to copy text I encountered a problem with pasting, the pasted content duplicates itself.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'https://gdquest.github.io/learn-gdscript/staging/#course/lesson-4-drawing-a-rectangle/practice-kGx0c7DD.tres'
2. Select Two rows of code
3. Enter a line break
4. Paste a code
5. See error

**Expected behavior**
Should paste:
```
move_forward(220)
turn_right(90)
```
Instead:
```
move_forward(220)
turn_right(90)move_forward(220)
turn_right(90)
```

**Video**
https://www.youtube.com/watch?v=REHTRIGFrtg

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 Pro Version	10.0.19044 Build 19044
 - Browser: Edge Version 106.0.1370.52 (Official build) (64-bit)

**Comment by NathanLovato** [comment] 2022-10-25 13:26
Duplicate of #698

**Closed by NathanLovato** 2022-10-25 13:26 UTC
Labels: bug, duplicate
