### ISSUE TITLE
Parser error: unknown character

### ISSUE THREAD

**Issue by danteKSA** [GDQuest/learn-gdscript#590] opened 2022-07-12 18:48 UTC
This bug happened to me twice in different ways, sometime i will write the code in a correct way and the app will execute it in a wrong way and sometime i will type the code in a correct way and the app will immediately tell me i failed without executing anything 

you can see in the pictures down that i have the right code, but it still tells me something is wrong 

**Screenshots**
![Base Profile Screenshot 2022 07 11 - 22 15 32 46](https://user-images.githubusercontent.com/109106328/178570779-99ce53d3-8230-447f-a458-3750244b6912.png)
![Base Profile Screenshot 2022 07 12 - 21 53 33 54](https://user-images.githubusercontent.com/109106328/178572237-e58f0631-d700-449c-99a1-571297edfedd.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10 i downloaded the app

**Comment by NathanLovato** [comment] 2022-07-13 04:27
Could you tell me which keyboard layout and language you're using? The error says that the compiler doesn't recognize one of the inserted characters. I'm not sure why but we can start with this.

**Comment by danteKSA** [comment] 2022-07-14 01:58
> Could you tell me which keyboard layout and language you're using? The error says that the compiler doesn't recognize one of the inserted characters. I'm not sure why but we can start with this.

My keyboard layout is QWERTY i also have Arabic and English languages in my computer but of course i only use English language when programming, maybe the existence of unsupported language like Arabic on my computer is somehow making the app freak out even when i'm not using it ?

**Comment by NathanLovato** [comment] 2022-08-04 12:40
Could you please copy the code you entered manually in the app and paste it here? To see if we can find unknown characters in there that get inserted. We can't reproduce the issue in the team.

**Comment by NathanLovato** [comment] 2022-10-04 14:44
Still missing the info/text needed to test, so I'm closing this for now as we can't look into the issue with the given info. If you can send us a text that causes this error, we will reopen the issue, test the bug, and see what we can do to fix it.

**Closed by NathanLovato** 2022-10-04 14:44 UTC
Labels: bug, missing info
