### ISSUE TITLE
Local keyboard layout is ignored in Chrome 94.0.4606.61

### ISSUE THREAD

**Issue by guppy42** [GDQuest/learn-gdscript#83] opened 2022-01-02 14:30 UTC
**Describe the bug**

The editor is remapping key to wrong symbols, eg sending a closing paretantesis ")" the editor outputs an opening "("

This makes the exercises a quite frustrating game of "guess the key combo"

**To Reproduce**
Steps to reproduce the bug:
1. Go to the beta website
2. Start tutorial
3. Start typing "Special characters" like ()&$*+-
4. Observe that the wrong character appears

**Expected behavior**
You would expect the key you pressed on your keyboard to match what the editor shows

**Information about your device (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Browser Chrome
 - Local keyboard layout Danish

**Additional context**
If for whatever reason you can't accept the characters sendt by the user you need to provide a way to specify the local keyboard layout so keys actually do what is expected

**Comment by NathanLovato** [comment] 2022-01-02 14:35
That's weird. This sounds like an issue on Godot's side as we use Godot's native text input. We'll investigate and see what we can do, thanks for letting us know. We have to see if it's specific to the Danish layout too - I think we tested with the Spanish layout already and didn't have this issue.

**Comment by NathanLovato** [comment] 2022-01-03 18:15
I just tested and can't reproduce the issue. I tried with the French Azerty keyboard, Spanish layout, as well as the Danish layout.

On my keyboard, pressing Shift 8 inserts a ( and Shift 9 inserts a ), etc., as indicated on my keyboard layout window on Linux.

![image](https://user-images.githubusercontent.com/12694995/147964867-1d385d5e-8f77-43b4-83f9-22f4c607c172.png)

Note that I'm on Pop_OS, so ubuntu-based, and we tried on Windows 10 too with the other computer.

**Comment by NathanLovato** [comment] 2022-01-04 13:30
I'm marking it as wontfix for now because we're unable to reproduce the bug. We need someone to figure out how to reproduce this, otherwise, we can't fix it.

**Comment by guppy42** [comment] 2022-01-05 07:30
I've figured out how to reproduce the issue and how to fix it ( locally at least )

the problem occurred with this chrome build : Version 94.0.4606.61 (Officiel version) (64-bit)

Which for what ever reason refused to update to a newer version until I manually uninstalled it and installed the latest version =
Version 97.0.4692.71 (Officiel version) (64-bit)

Not sure why using a slightly out of date chrome version would result in broken input detection, but It might be worth doing a check for it and warning the user

**Comment by NathanLovato** [comment] 2022-01-05 13:29
Okay, if that was a Chrome bug, then there's not much we can do about it. I'll close the issue.

**Closed by NathanLovato** 2022-01-05 13:29 UTC
Labels: bug, help wanted, wontfix
