### ISSUE TITLE
Screen not scaling

### ISSUE THREAD

**Issue by maranr** [GDQuest/learn-gdscript#76] opened 2021-12-31 19:32 UTC
Issue:
When I try and change my browser screen size (width) the display does not scale properly. When I change the width of my browser, I get black bars. If I make it smaller, the text is unreadable. The screen needs to be responsive and fill the screen or somehow be fixed. I can't seem to get it back to the normal size I started off with.  

Steps to reproduce:
Run the app. 
Resize the window

**Expected behavior**
I expect the screen to scale better than it does. Either fill the screen and the text should not shrink down. 

**Screenshots**
See attached

**Information about your device (please complete the following information):**
Google Chrome
Windows 10
**Additional context**
![gdquest_app_resize2](https://user-images.githubusercontent.com/31901090/147837067-3b1267f7-9348-450c-b519-b5729ca240d6.png)
![gdquest_app_resize1](https://user-images.githubusercontent.com/31901090/147837069-426de167-b739-416b-8ee7-8bc4bed68b9d.png)

**Comment by NathanLovato** [comment] 2022-01-02 19:38
Duplicate of #37

This should already be fixed by #70 (in the next release).

**Closed by NathanLovato** 2022-01-02 19:38 UTC
Labels: bug, duplicate

**Comment by NathanLovato** [comment] 2022-01-02 19:40
Note that if you have a vertical display, the app won't work for you. It's not a regular website: it's a game running in your web browser, designed for landscape displays.
