### ISSUE TITLE
HTML displayed in lessons 11 and 13

### ISSUE THREAD

**Issue by zircher** [GDQuest/learn-gdscript#199] opened 2022-01-28 02:47 UTC
The second question in this lesson is displaying HTML tags.

**Comment by zircher** [comment] 2022-01-28 03:43
The last quiz question on Lesson 13 also has this issue.

**Comment by johnnygossdev** [comment] 2022-01-28 11:34
This isn't happening on my browser (Firefox). Can you supply more information please? What browser are you using? If you could supply screenshots, that would help too.

**Comment by NathanLovato** [comment] 2022-01-28 13:19
Can't reproduce. Could you share a screenshot? Also, on which browser is this happening and on which OS?

**Comment by zircher** [comment] 2022-01-28 14:40
Using Brave (Chromium) on Win10.  No screen shot since the questions disappear when answered.  Will post if I see it again.

**Comment by NathanLovato** [comment] 2022-01-28 14:48
Was it perhaps bbcode inside quizzes? like [b]Question here[/b]? If so, the bug's already fixed and a duplicate of #179 #195 etc.

Or is it really HTML code, like <p>...</p>? That shouldn't be possible as the app uses WebGL and not HTML internally.

**Comment by zircher** [comment] 2022-01-28 14:57
Ah yes, it was the BB code.  Sorry about the confusion there.  But, it did not happen for all questions, only a couple.

**Comment by NathanLovato** [comment] 2022-01-28 20:26
Okay, then it's already fixed.

**Closed by NathanLovato** 2022-01-28 20:26 UTC
Labels: duplicate, content
