### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by Maestro-SJ** [GDQuest/learn-gdscript#782] opened 2023-02-16 17:10 UTC
### Discussed in https://github.com/GDQuest/learn-gdscript/discussions/781

<div type='discussions-op-text'>

<sup>Originally posted by **Maestro-SJ** February 16, 2023</sup>
Is "learn to code from zero" io website available for Android? If it is really available, then why I can't use my keyboard to type code in practice session</div>

**Comment by NathanLovato** [comment] 2023-02-16 20:10
No, android isn't supported. See #778 for more info
Duplicate of #778

**Closed by NathanLovato** 2023-02-16 20:10 UTC
