### ISSUE TITLE
Lesson 10: app crashes if running a second time

### ISSUE THREAD

**Issue by Fallenhero83** [GDQuest/learn-gdscript#560] opened 2022-06-13 05:51 UTC
**Describe the bug**
App Freezes if practice is run for a second time

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'Lesson 10: Creating Circular Movement'
2. Click on 'Run a second time'

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Chrome

**Comment by Fallenhero83** [comment] 2022-06-13 06:13
All happened on Lesson 11: Time Delta - Moving in a Circle Using Delta

**Comment by MissLav** [comment] 2022-07-13 17:19
having the same issue

**Comment by MissLav** [comment] 2022-07-13 17:20
move_local_x in lesson 11 crashes for me on firefox linux

**Comment by NathanLovato** [comment] 2022-07-13 17:53
Could you please share the exact code you used that caused the issue?

**Comment by MissLav** [comment] 2022-07-13 17:58
heres a screenshot of it being frozen 
![image](https://user-images.githubusercontent.com/51702517/178799761-0e506852-3557-4589-bd1c-d417baf20b80.png)

**Comment by MissLav** [comment] 2022-07-13 17:59
also happened on one the previous tests 
![image](https://user-images.githubusercontent.com/51702517/178799963-d370e6e4-10d7-4c05-bd49-28894e4a77d6.png)
screenshot i sent  to a friend

**Comment by NathanLovato** [comment] 2022-07-13 18:13
I could reproduce the freeze, but have no idea what's causing it. The error's not helpful, unfortunately. In the meantime, I recommend downloading one of the desktop versions; https://gdquest.itch.io/learn-godot-gdscript

**Comment by henriquelalves** [comment] 2022-09-02 00:18
The freeze appears to  be fixed on bleeding edge, most likely because of the Debug build.

**Comment by NathanLovato** [comment] 2022-09-02 06:08
Thanks!

**Closed by NathanLovato** 2022-09-02 06:08 UTC
Labels: bug

**Comment by KareemFarrag** [comment] 2022-11-20 12:21
this lesson crash on windows 10 exe when run code at full screen
