### ISSUE TITLE
In chapter 7 some [code] blocks are not shown

### ISSUE THREAD

**Issue by hooger** [GDQuest/learn-gdscript#699] opened 2022-10-10 12:36 UTC
![kép](https://user-images.githubusercontent.com/12232146/194867248-f9ab3c04-341b-411a-b4ea-9dd943468823.png)

On the attached image, the underlined double white spaces should contain x and y, which is missing, yet in the src (`https://github.com/GDQuest/learn-gdscript/blob/main/course/lesson-7-member-variables/lesson.tres`), the following is present:

```
For example, the [code]position[/code] we mentioned has two coordinates: [code]x[/code] and [code]y[/code].

It's the same for the [code]scale[/code]: it has [code]x[/code] and [code]y[/code] sub-variables. They respectively control the horizontal and vertical size of the game entity.
```

**Comment by NathanLovato** [comment] 2022-10-10 13:28
This is already fixed in the latest version, but it is possible that your browser cached the previous release and is not downloading the latest update.

Could you please click on the URL bar in your web browser and press Ctrl Shift R to clear the cache and re-download the app? That should solve the issue.

At least on our end, in both firefox and brave, these are visible. So I'll close for now, but if you still have the issue after clearing the cache, please let me know, and we will reopen the issue.

**Comment by hooger** [comment] 2022-10-10 13:43
Well, I'm not sure, if it is a caching issue, as hitting Ctrl+Shift+R, or hitting Ctrl+R in quick succession in Firefox does not help, also opening a private browser tab, or opening the tab in chromium (which I haven't done so far) doesn't solve the issue. :thinking: Can something else cache the content? Like some enterprise level network device?

**Comment by NathanLovato** [comment] 2022-10-10 14:36
I don't know that something else could cause the cache but a private tab should bypass any cache anyway. We can't reproduce the issue unfortunately, but we'll keep this open to see if we can reproduce at some point

**Comment by NathanLovato** [comment] 2022-10-11 11:54
@henriquelalves  could you see if this happens to you? I can't reproduce the bug

**Comment by hooger** [comment] 2022-10-12 13:14
Well, I reproduce it basically everywhere now. I saw it in lesson 8 IIRC and definitely see it in lesson 11 practice. See attached image: 
![kép](https://user-images.githubusercontent.com/12232146/195352378-282c0843-ef92-410d-b173-a8cde297b789.png)

**Comment by hooger** [comment] 2022-10-12 13:24
Another, in lesson 12, practice 1
![kép](https://user-images.githubusercontent.com/12232146/195354498-96e888d3-43c4-4cae-b513-ce96db3cc231.png)

**Comment by hooger** [comment] 2022-10-12 13:25
Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.19.11-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 8 × 11th Gen Intel® Core™ i7-11370H @ 3.30GHz
Memory: 15,4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: TUXEDO
Product Name: TUXEDO InfinityBook Pro 14 Gen6

Firefox:
```sh
pacman -Qs firefox
local/firefox 105.0.1-1
    Standalone web browser from mozilla.org
```

**Comment by hooger** [comment] 2022-10-17 11:01
It is working know. What surprising is, that I always have seen the Godot logo with the progress bar, and than the kids in the classrom image, so I guess it always loaded everything from zero. Whatever, it seems to be good now. I let closing the issue to you.

**Comment by NathanLovato** [comment] 2022-10-17 11:10
Thanks! I'm really glad that you can enjoy the app now.

It's a weird issue, but it's in the browser, and honestly, I don't know why it's happening to you. There's necessarily a technical reason, but unfortunately, browsers are complicated environments, we add a complicated layer by making apps in Godot, and we're constantly on tight time budgets, so it limits our ability to look into rare bugs.

That's also why we provide desktop versions of the app, at least in general, this gives users a reliable workaround in case they encounter browser-specific issues we lack the time to fix.

**Closed by NathanLovato** 2022-10-17 11:10 UTC
Labels: bug
