### ISSUE TITLE
The box with extra info for underlined definitions doesn't scale correctly

### ISSUE THREAD

**Issue by IkutiDev** [GDQuest/learn-gdscript#441] opened 2022-03-10 20:28 UTC
**Describe the bug**
When you have underlined terms that you press to show the box of extra information for specific term, the size of the box remembers the last box size instead of updating when we press it. So for example when we function which has a very big box full of information, than we press body which has shorter explanation, the size of the box is too big. The size is correct when we press body second time after that. 

It also is fine if we first press underlined link with smaller box and than press the link with bigger box, since the box will enlarge to correct size.

**To Reproduce**
Steps to reproduce the bug:
1. Press any underlined link that gives extra information
2. Press another underlined link that gives extra information but less in size.
3. Have box with a lot of empty space since the box hasn't shrunk to correct size.

**Expected behavior**
The box should shrink/enlarge to the correct size of specific underlined link.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/40697587/157748817-dc5316cf-a7fe-44c4-a8f2-e1602bff2a4b.png)
![obraz](https://user-images.githubusercontent.com/40697587/157748886-f6003651-2090-4e4a-aba3-a68ffc2bd639.png)

**Information about your device (please complete the following information):**
- Windows
- Desktop app for windows

**Comment by NathanLovato** [comment] 2022-03-11 07:47
Already fixed, duplicate of #436

**Closed by NathanLovato** 2022-03-11 07:47 UTC
Labels: bug, duplicate
