### ISSUE TITLE
In mobile, We can't Edit code when they tell us to

### ISSUE THREAD

**Issue by SillyHell** [GDQuest/learn-gdscript#824] opened 2023-05-23 17:25 UTC
When they tell us to edit a code, like the lesson "Fix Your First error", We just can't remove the space its like not having a keyboard to remove. 
I can't use pc to cause mine is pretty old and broken.

fixxing that issue will help me alot to learn GDSript and also for my futur project!
Thanks
![Screenshot_20230523_192356_Chrome](https://github.com/GDQuest/learn-gdscript/assets/131562567/7d01fb43-e0fd-421f-94ea-9de7de69574c)

**Comment by NathanLovato** [comment] 2023-05-24 05:26
Mobile keyboards aren´t supported unfortunately. We won't support mobile devices fully with this app. However we're looking into mobile support with the Godot 4 remake. Closing as duplicate of #778

**Closed by NathanLovato** 2023-05-24 05:26 UTC
Labels: bug
