### ISSUE TITLE
Cannot Complete Both Lesson 7 practices

### ISSUE THREAD

**Issue by killbent** [GDQuest/learn-gdscript#80] opened 2022-01-01 18:37 UTC
**Describe the bug**
For the first practice, no matter what I type into the code, when I run the program the screen freezes, the buttons go grey, and I can't scroll or click anything. I have to reload the page to fix it. Even when I press "show solution" and run the code from that it still freezes. 

However, the second practice will only freeze if the solution is correct, it seems. As I can get errors like normal, unlike what's happening in the first practice session.

**To Reproduce**
Steps to reproduce the bug:
1. Go to either practice session from lesson 7
2. For session 1, click on Run. For session 2, click Show Solution and click Run.
3. See error

**Expected behavior**
Should either give me an in-game error, or complete the practice session.

**Screenshots**
![girlhelp](https://user-images.githubusercontent.com/96953816/147857421-b1184c2e-b689-491b-a3ee-f5e1365ff316.png)

![girlhelp2](https://user-images.githubusercontent.com/96953816/147857619-9453a4d3-c1a2-42bb-826f-8c180fdf3d5a.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 10
 - Browser: Firefox

**Comment by allkhor** [comment] 2022-01-01 19:34
Duplicate of #67, it's about level 7 not 6...

**Comment by killbent** [comment] 2022-01-01 20:45
> Duplicate of #67, it's about level 7 not 6...

Oh whoops. I got confused since in the index it's listed as 7, but in the actual lesson it's 6.

![whoopsy](https://user-images.githubusercontent.com/96953816/147859835-fdf6d18a-313f-4b1e-a19b-9d72de95fe9b.png)

![whoopsy2](https://user-images.githubusercontent.com/96953816/147859836-756021dc-b770-4b26-a6a2-4755e024af77.png)

**Comment by NathanLovato** [comment] 2022-01-02 13:05
I'll leave this as it also covers another assignment. It's lesson 7, the title's correct, but there's a little bug with lesson numbers in the currently deployed version of the app.

**Closed** 2022-01-02 18:24 UTC
Labels: bug, duplicate
