### ISSUE TITLE
Lesson 15 - missing closing parenthesis

### ISSUE THREAD

**Issue by QWERTIOX** [GDQuest/learn-gdscript#908] opened 2024-01-16 19:05 UTC
**Issue description:**
In the "Vectors are great for games" and "Using vectors to change the position" sections, in the example the closing brackets are missing

**Screenshots:**
![image](https://github.com/GDQuest/learn-gdscript/assets/64694795/5654f5ca-73ec-474f-acd2-28f571b6b9eb)
![image](https://github.com/GDQuest/learn-gdscript/assets/64694795/b60cc4ec-55b3-443b-ab7f-49e79e6206dc)

**Comment by QWERTIOX** [comment] 2024-01-16 19:22
![image](https://github.com/GDQuest/learn-gdscript/assets/64694795/3861aa7e-ea1d-40b8-b65d-c846e2392d0c)
it fixed when i wasn't looking on the application for some time

**Comment by NathanLovato** [comment] 2024-01-16 19:34
It's a text wrapping issue in Godot 3. Thanks for the report but this one's a duplicate of #99

**Closed by NathanLovato** 2024-01-16 19:34 UTC
Labels: content
