### ISSUE TITLE
Lesson 20 - Back to the drawing board can't be solved

### ISSUE THREAD

**Issue by nestor-2099** [GDQuest/learn-gdscript#513] opened 2022-05-05 01:41 UTC
**Describe the bug**
The system always gives the message "At least one of the rectangles does not have the expected size", even when using the default solution.

I tested with:
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for size in rectangle_sizes:
		draw_rectangle(size.x, size.y)
		jump(size.x, size.y)

==================
var rectangle_sizes = [Vector2(200, 120), Vector2(140, 80), Vector2(80, 140), Vector2(200, 140)]

func run():
	for size in rectangle_sizes:
		draw_rectangle(size.x, size.y)
		jump(size.x, 0)

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 20
2. Click on Solution
3. Click on Use Solution
4. Click on Run

**Expected behavior**
The lesson should be solved.

**Screenshots**
![drawing-board-error](https://user-images.githubusercontent.com/12819175/166852560-9c5a3728-7f42-4770-bd36-bee62e375b06.jpg)

**Information about your device (please complete the following information):**
 - Operating System: Windows
 - Browser: Firefox

**Comment by NathanLovato** [comment] 2022-05-05 05:15
Duplicate of #505

**Closed by NathanLovato** 2022-05-05 05:15 UTC
Labels: bug
