### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by ElProfessor-spain** [GDQuest/learn-gdscript#993] opened 2024-09-24 02:34 UTC
The mobile support for this version is not good. When on the practice, when i need to edit the code and click on the part that needs to be edit, the keyboard does not shows up.

**Comment by NathanLovato** [comment] 2024-09-24 06:20
Hi, there's no mobile support currently. This is a duplicate of #847, closing

**Closed by NathanLovato** 2024-09-24 06:20 UTC
Labels: enhancement
