### ISSUE TITLE
The text is blury...

### ISSUE THREAD

**Issue by DhruvSiri** [GDQuest/learn-gdscript#547] opened 2022-06-09 21:16 UTC
Whenever I open the app on my Macbook or on the browser the text appears rather blurry. While most of the pictures I am looking at don't seem to be like this.

**Comment by NathanLovato** [comment] 2022-06-10 08:23
Duplicate of #381 

I invite you to download the Mac version or try with another web browser if you face this issue, for now.

**Closed by NathanLovato** 2022-06-10 08:23 UTC
