### ISSUE TITLE
Selectable text

### ISSUE THREAD

**Issue by Kvazzr** [GDQuest/learn-gdscript#512] opened 2022-05-03 20:38 UTC
As a non-native English speaker, sometimes I come across new words in this app and need to look up their meaning to make sure I understand them correctly. It would be a little more convenient if I could select and copy text directly from the app, instead of typing it manually.

**Solution I'd like**
Make text in the main text block selectable and copyable.

**Comment by NathanLovato** [comment] 2022-05-04 04:55
Duplicate of #68

**Closed by NathanLovato** 2022-05-04 04:55 UTC
Labels: enhancement
