### ISSUE TITLE
Text Wrap Issue (I think)

### ISSUE THREAD

**Issue by prof-egg** [GDQuest/learn-gdscript#804] opened 2023-03-07 23:13 UTC
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
I'm on lesson 15 about the modulo operator, reading about its use cases, playing with the widgets, etc. For the image I linked below, I was confused on what I was looking at code wise, especially since it didn't even have the modulo it was referencing. I then realized, that lines "2" and "3" were the same line, and that the modulo got cut off when the text wrapped. At least, I'm assuming that's what happened. Maybe there is some magic gdscript syntax I just don't know yet.
![image](https://user-images.githubusercontent.com/69015627/223574358-e6170d38-dcb3-4b50-b248-72a3defbe143.png)

**What is the expected behavior?**
I'm assuming the code isn't supposed to wrap in the image like that

**Comment by NathanLovato** [comment] 2023-05-06 05:46
Thanks for the report. and for helping triage. Indeed it's due to #99, and the problem is due to Godot 3's text wrap, it's unfortunately not something we have found a fix to.

Closing as we're tracking this in #99

**Closed by NathanLovato** 2023-05-06 05:46 UTC
