### ISSUE TITLE
Lesson 20, practise "Back to the drawing board"

### ISSUE THREAD

**Issue by ikoroki** [GDQuest/learn-gdscript#508] opened 2022-04-29 22:17 UTC
**Describe the bug**

App says at least one of the rectangles have the wrong size. Wrote the code for my self first, got the error, then clikced Solution, and noticed my code was identical. Tried some more times, and even clicked "Use solution", still got the same error.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Lesson 20, practise "Back to the drawing board"
2. Click on "Solution" then "Use solution"
3. Click on "Run"

While writing this: Reproduced the error one more time. Then tried another time to take Screenshots, but the lesson completed it self without the error.

**Expected behavior**

Expected to complete the excercise

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/97807602/166075596-8b14682e-1d3d-4b1b-bb90-74728101e059.png">

**Information about your device (please complete the following information):**
On Windows on Chrome
**Additional context**
Failed to reproduce the error more than 3 times.

**Comment by NathanLovato** [comment] 2022-04-30 05:13
Duplicate of #505

**Closed by NathanLovato** 2022-04-30 05:13 UTC
Labels: bug, duplicate
