### ISSUE TITLE
The keyboard doesn't show up in mobile (im using tablet (Xiaomi pad 6))

### ISSUE THREAD

**Issue by AkzinNoob** [GDQuest/learn-gdscript#945] opened 2024-04-19 12:06 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'open your mobile'
2. Click on 'its start from lesson 2 where u need to write and delete or what ever keyboard needed for'
3. Scroll down to ' just try to write from mobile'

**Expected behavior**
(Simply keyboard is not showing up im using kinda a good mobile device so i learning programming on it but i cant learn probably cus of the bug )

**Screenshots**
If applicable, drag and drop screenshots here to help explain your problem.

![Screenshot_2024-04-19-14-57-26-719_com android chrome](https://github.com/GDQuest/learn-gdscript/assets/167532754/ad9482f9-995a-4ecd-ae00-ef22e9e117cb)

Idk if that mean u can see the screen shot now

**Information about your device (please complete the following information):**
 - Operating System: [ mobile android]
 - Browser: [Chrome]

**Additional context**
(I tried another browser but same problem if it works i wont be here writing)

**Comment by AkzinNoob** [comment] 2024-04-19 21:19
Hmmm no one have solution?

**Comment by NathanLovato** [comment] 2024-04-20 15:30
Mobile devices aren't fully supported. You can learn more here: #847 

If you want to use the app on a tablet, you'll need to use a physical keyboard. Closing as it's a duplicate of #847

**Closed by NathanLovato** 2024-04-20 15:30 UTC
Labels: bug
