### ISSUE TITLE
L10 Practice 2: web build crashes if you click stay after completing practice and run again

### ISSUE THREAD

**Issue by return2monki** [GDQuest/learn-gdscript#566] opened 2022-06-23 13:34 UTC
It crashes at 2nd question in 10th lesson not sure about others.

 - Operating System: Windows
 - Browser: Chrome

**Comment by NathanLovato** [comment] 2022-08-05 07:41
After testing, it seems specific to this one

**Comment by NathanLovato** [comment] 2022-08-05 08:06
Actually it's a duplicate of #560, closing to keep just one issue for this

**Closed by NathanLovato** 2022-08-05 08:06 UTC
Labels: bug
