### ISSUE TITLE
Practice 3 in lesson 6 does not fit on screen. 

### ISSUE THREAD

**Issue by Angrycrow** [GDQuest/learn-gdscript#596] opened 2022-07-20 02:11 UTC
**Describe the bug**
Unable to read the directions in practice 3 of lesson 6 because of UI windowing. 

**To Reproduce**
Steps to reproduce the bug:
1. Play lesson 6 in full screen.

**Expected behavior**
I expect to be able to read the directions alongside the rest of the app.. But this is cut off on the left side.. Apparently a different window size is expected in the UI layout. 

**Screenshots**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/2450703/179880732-d6cfa6c7-03ab-447d-9eed-72fee6d8b984.png">

**Information about your device (please complete the following information):**
 - Operating System: macOS
 - Browser: Safari, 
But this bug was found running the app from the Godot Project launcher. 

**Additional context**

**Comment by NathanLovato** [comment] 2022-07-22 14:39
Same issue as #543

**Comment by NathanLovato** [comment] 2022-08-04 11:51
Closing as it's a duplicate of #543

**Closed by NathanLovato** 2022-08-04 11:51 UTC
Labels: bug
