### ISSUE TITLE
"in" expected after indentifier

### ISSUE THREAD

**Issue by Geostrike123455** [GDQuest/learn-gdscript#750] opened 2022-12-06 14:33 UTC
When I try to create a for loop If would tell me I need to add in after my identifier and I do so but nothing happens

I typed out 
func run():
       for rectangle_sizes in draw_rectangle:
                    draw_rectangle(rectangle_sizes)
                    jump()

and this was the issue I encountered. I'm in lesson 20 in the second practice exercise

"in" expected after identifier

**Comment by NathanLovato** [comment] 2022-12-18 15:56
If the issue is that your code doesn't pass, it's normal, it's incorrect. I've tried a couple of code combinations, including the code you listed, and I get error underlines and error message explanations, which is what should be happening. Closing as there doesn't seem to be a bug here. If there is a bug could you please tell us the precise steps to reproduce it?

**Closed by NathanLovato** 2022-12-18 15:56 UTC
Labels: bug
