### ISSUE TITLE
GDQuest Boy moves up

### ISSUE THREAD

**Issue by RetroApe** [GDQuest/learn-gdscript#703] opened 2022-10-11 18:40 UTC
**Describe the bug**
In Lesson 3. We Stand on the Shoulders of Giants, there is an example where the character is supposed to move right and down, but he moves left and up.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [['...'](https://gdquest.github.io/learn-gdscript/)](https://gdquest.github.io/learn-gdscript/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres)
2. Scroll down to the second run() example.
3. Press run()

**Expected behavior**
It is clearly stated how the character moves down. My supposition is that he should move right as well.
So it is expected that he should move right and down.

**Screenshots**
![image](https://user-images.githubusercontent.com/113673335/195162931-fa729ee2-8c09-4e70-99f8-1cc58fb049ea.png)

P.S. Apologies if I am wrong and I took your time for nothing. I am new at this.

**Comment by NathanLovato** [comment] 2022-10-12 04:42
Already fixed, duplicate of #694, will be OK in the next release

**Closed by NathanLovato** 2022-10-12 04:42 UTC
Labels: bug, duplicate
