### ISSUE TITLE
CTRL+V pastes text twice

### ISSUE THREAD

**Issue by SuperSiliconosis123** [GDQuest/learn-gdscript#738] opened 2022-11-13 17:55 UTC
**Describe the bug**
When using the keyboard shortcut ctrl+v, the "paste" action is completed twice instead of once.

**To Reproduce**
Steps to reproduce the bug:
1. Go to any text editor on gdquest.github.io
2. Copy some text (ctrl+c)
3. Paste the text (ctrl+v)
4. Observe that the text you copied was pasted twice

**Expected behavior**
I expected the text to only be pasted once

**Information about your device:**
 - Operating System: Chrome OS (107.0.0.0)
 - Browser: Chrome

I suspect that chrome pastes the text and then the text editor also pastes the text

**Comment by NathanLovato** [comment] 2022-11-14 11:17
Duplicate of #698

**Closed by NathanLovato** 2022-11-14 11:17 UTC
Labels: bug, duplicate
