### ISSUE TITLE
cut text

### ISSUE THREAD

**Issue by AredesDiego** [GDQuest/learn-gdscript#565] opened 2022-06-22 13:13 UTC
There is a problem in the application text, where the text is displayed in a strange and cropped way.
-I am using microsoft edge browser.
-I'm using it in the Spanish language.
-It's chapter 6 in practice 3 (that practice is called: draw squares of any size.
-This problem persists even if I put the full screen (as shown in the second image).
.......................................................................................................................................................................
I just saw that checks were open, and apparently that is what generates the text bug (as shown in the third image)

![Captura en pantalla completa](https://user-images.githubusercontent.com/104737872/175037509-bbc29cb2-2797-4846-9235-1a81e5882e38.PNG)
![Captura](https://user-images.githubusercontent.com/104737872/175037512-3311fe74-a471-484b-bf33-57e21d9e4887.PNG)
![Captura solucion de error](https://user-images.githubusercontent.com/104737872/175042973-f7f0cf5e-aff4-43d2-b0ab-9c9c280e0932.PNG)

**Comment by NathanLovato** [comment] 2022-06-22 14:05
Duplicate of https://github.com/GDQuest/learn-gdscript/issues/543

**Closed by NathanLovato** 2022-06-22 14:05 UTC
Labels: content
