### ISSUE TITLE
Underlined word pop-up, remembers previous pop-up height if it was taller

### ISSUE THREAD

**Issue by duianto** [GDQuest/learn-gdscript#436] opened 2022-03-07 23:26 UTC
**Describe the bug**

The underlined word pop-up, remembers the previous pop-up height if it was taller.
This leaves a lot of empty space below the text when the next pop-up has less text.

**To Reproduce**
Steps to reproduce the bug:
1. Go to https://gdquest.github.io/learn-gdscript/staging/#course/lesson-3-standing-on-shoulders-of-giants/lesson.tres
2. In the third paragraph, click on the underlined last word: `library`
3. See that the pop-up fits the text.
4. Under the heading: `You'll always use a lot of existing code`
5. In the third paragraph, click on the underlined second word: `function`
6. See that the pop-up also fits the text.
7. Move the mouse pointer outside the pop-up so that it hides
8. Click on the same underlined word, as in step 2: `library`
9. See that the pop-up has the same height as the `function` pop-up
This leaves a lot of empty space below the text.
10. Move the mouse pointer outside the pop-up to hide it.
11. And click on `library` again
12. See that it now has the correct height.

**Expected behavior**

The pop-up height should match the text every time,
so that there isn't a lot of empty space below it.

**Screenshots**

https://user-images.githubusercontent.com/13420573/157134860-9fba70e4-2e4f-4537-aadf-1bc949fbff97.mp4

**Information about your device (please complete the following information):**

 - Operating System: Windows 10 21H2
 - Browser: Microsoft Edge 98.0.1108.62 (Official build) (64-bit)

**Comment by NathanLovato** [comment] 2022-03-08 07:21
After a couple clicks it resets as expected but in some cases it doesn't. The code's currently using a deferred set, gotta check if there's a signal to resize the panel after the text changed size - the issue is rich text labels don't update their height reliably.

**Comment by NathanLovato** [comment] 2022-03-08 07:55
Closed by d4f91f36afc74f91e0e6e55393a0f74753b5549f

**Closed by NathanLovato** 2022-03-08 07:55 UTC
Labels: bug
