### ISSUE TITLE
Code block hide part of the content when line wrap (and random black box around the lesson)

### ISSUE THREAD

**Issue by Zykino** [GDQuest/learn-gdscript#1022] opened 2024-11-10 10:21 UTC
**Describe the bug**
Code blocks that are longer than a line keep some of the code hidden (see selected `Vector2`, it isn’t complete).
![image](https://github.com/user-attachments/assets/7c247c4f-e0fd-4422-8dd3-051026278edb)

I’m not sure it is related, but I also (kind of randomly) get black bars around the lesson.
![image](https://github.com/user-attachments/assets/ee7f7a93-632a-4fc0-b2ee-21a43a0bbbdf)

**To Reproduce**
Steps to reproduce the bug:
1. Use french language (maybe?)
2. Go to lesson 18 (saw it earlier, and I guess later)
3. Scroll down to the last code example, before the exercises

**Expected behavior**
Seeing the full code in the code block

**Information about your device (please complete the following information):**
 - Operating System: Linux pop-os (ubuntu based)
 - Browser: Firefox 131.0.3

**Additional context**
* Wayland
* Double monitor in 1080p
    * The application is full screened from https://school.gdquest.com/courses/learn_2d_gamedev_godot_4/learn_gdscript/learn_gdscript_app#lets-get-started on 1 monitor

**Comment by NathanLovato** [comment] 2024-11-19 10:31
Thank you for the report! This is a known issue that we unfortunately don't have much control over: #99

Closing as it's a duplicate of an existing issue

**Closed by NathanLovato** 2024-11-19 10:31 UTC
Labels: bug
