### ISSUE TITLE
Lesson 20 practice throwing error even thouhg the solution is correct (app)

### ISSUE THREAD

**Issue by czmatejt9** [GDQuest/learn-gdscript#548] opened 2022-06-10 12:56 UTC
**Describe the bug**
In the second practice in lesson 20 (back to the drawing board) when I run my code it shows error that one or more rectangles does not have expected size even though they all clearly have. This also happens with copied solution.

**To Reproduce**
Steps to reproduce the bug:
Run the code in the second practice in lesson 20

**Expected behavior**
It should succefully pass the practice

**Screenshots**
![image](https://user-images.githubusercontent.com/105561491/173068846-0613bf0c-176e-404c-8675-f54d6ab791f3.png)

**Information about your device (please complete the following information):**
 - Operating System: Windows 11
 - Application

**Comment by NathanLovato** [comment] 2022-06-10 14:52
Already fixed, duplicate of #544

**Closed by NathanLovato** 2022-06-10 14:52 UTC
Labels: bug
