### ISSUE TITLE
Lesson 3 Bug with sprite demonstration 

### ISSUE THREAD

**Issue by Carcingetorix** [GDQuest/learn-gdscript#707] opened 2022-10-12 15:14 UTC
In the lesson, giving an explanation as to how move_local_x and move_local_y works the explanation rightly states: "With positive values (20), the code above moves the robot to the right and down."

The robot sprite demonstration is bugged, therefore, because it didn't move to the right and down. It moved to the left and up.

![bug](https://user-images.githubusercontent.com/107487992/195381264-e7ae4116-820c-4ec7-8b64-05272880421a.JPG)

**Comment by NathanLovato** [comment] 2022-10-12 15:29
Duplicate of #694

**Closed by NathanLovato** 2022-10-12 15:29 UTC
Labels: bug, duplicate
