### ISSUE TITLE
Lesson 7 Practices freeze upon completion

### ISSUE THREAD

**Issue by Pebbles01** [GDQuest/learn-gdscript#88] opened 2022-01-03 03:09 UTC
The title really says it all but when I press run after entering the correct code, or any code that doesn't give errors, the app freezes.

I completed all other lessons but for 7 I can't complete the practices.
The first one. Notice the run button being grey from being pressed.
![image](https://user-images.githubusercontent.com/97007077/147896854-9a15a668-5be8-4f7b-a1ee-1385da666a0d.png)

Here's the second one, also after pressing run.
![image](https://user-images.githubusercontent.com/97007077/147896889-875fd8d6-9d2e-445b-8e4c-0cc5f9751fc9.png)

For the bug report I just showed the solution but I also tried reversing the numbers, writing the code to draw it as learnt in previous lessons.
Pressing F5 doesn't refresh the page only through the refresh button from the browser or going back to the course home page through the link.

I run the app on windows 10 in Opera GX as well as Chrome.

Not sure if this is already know but I don't see it in the github hub so thought I'd mention it.

**Comment by allkhor** [comment] 2022-01-03 04:10
Duplicate of #80, fixed with #82.

**Closed** 2022-01-03 13:18 UTC
Labels: bug
